[package]
name = "stripe-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
openapiv3 = "2"
prettyplease = "0"
quote = "1"
serde_json = "1"
syn = "2"